version: "3.9"
name: "L0"
services:
  db:
    image: postgres:alpine
    container_name: db
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    restart: always
