version: "3.9"
name: "L0"
services:
  db:
    image: postgres:alpine
    container_name: db
    env_file:
      - .env
    ports:
      - "5432:5432"
    restart: always

  nats-streaming:
    image: nats-streaming:alpine
    container_name: nats-streaming
    ports:
      - "4222:4222"
      - "8222:8222"
    restart: always
